### ISSUE TITLE
Lack of Documentation 

### ISSUE THREAD

**Issue by nabobalis** [nabobalis/sunkit-sst#5]
Seriously, I forgot how to use this myself sometimes.

**Comment by agneet42** [comment]
@nabobalis , can I help?

**Comment by nabobalis** [comment]
@agneet42 If you would like. It has been a while since I looked at what documentation is missing, I just know that it is missing. 

Also, checking RTD to make sure the docs are building correctly.

**Comment by agneet42** [comment]
Sure, I'll get back to you.

**Comment by Cadair** [comment]
They are not building correctly, I think your webhook setup is buggered.

**Comment by nabobalis** [comment]
Yes, it does look like the webhook is buggered.

**Comment by agneet42** [comment]
gui.rst has no entries. Was it intended to keep it that way or does it need documentation?

**Comment by nabobalis** [comment]
The plan for that was a short user guide to explain how to use the GUI. Since it how it works is quite opaque and does not offer much user feedback.

**Comment by agneet42** [comment]
Okay. Can I help in writing down the short user guide then?  Or do I check on whether it works with any Stokes and report back on that Issue?

**Comment by nabobalis** [comment]
If you want to write down a short user guide, I am happy to check it. 

Stokes wise, I got it working on the stokes_wip branch, but the code isn't tidy enough yet to merge in my opinion.

**Comment by agneet42** [comment]
@nabobalis, okay. I'll get to it.
